version: "3.9"
services:
  db:
    container_name: manga_store_db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} 
      POSTGRES_DB: manga_store
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
